-- Industry pricing refresh for 2026 with multi-source attribution.
-- Generated by scripts/generate_migration.py

alter table public.industry_rates
  add column if not exists source_urls text[] not null default '{}';

with seed_rates as (
  select * from (
    values
      ('ir_faucet_repair', 'Fixtures', 'Faucet Replacement', 'Faucet Replacement', 'Repair or replace leaking faucet and reconnect fittings', 139.50, 223.20, 379.44, 0.9, 1.4, 2.4, array['faucet','fixture','leak','replace'], 'Angi | Homeguide | Housecallpro 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm','https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_toilet_replacement', 'Fixtures', 'Toilet Replacement', 'Toilet Replacement', 'Replace toilet and reset seals and water connection points', 276.67, 442.67, 752.54, 1.7, 2.8, 4.8, array['toilet','fixture','replace'], 'Angi | Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm']),
      ('ir_disposal_replacement', 'Fixtures', 'Garbage Disposal Replacement', 'Garbage Disposal Replacement', 'Replace jammed or failed garbage disposal unit', 283.61, 418.33, 553.06, 1.8, 2.6, 3.5, array['garbage','disposal','replace'], 'Homeguide | Housecallpro 2026 normalized', array['https://homeguide.com/costs/faucet-installation-cost','https://homeguide.com/costs/garbage-disposal-installation-cost','https://homeguide.com/costs/plumber-cost','https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_kitchen_drain', 'Drain Services', 'Kitchen Drain Clearing', 'Kitchen Drain Clearing', 'Clear kitchen drain obstruction and restore normal flow', 103.12, 164.99, 278.12, 0.8, 1.2, 2.0, array['kitchen','drain','clog'], 'Homeguide | Housecallpro 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_main_drain', 'Drain Services', 'Main Drain Snaking', 'Main Drain Snaking', 'Snake main line and verify full drainage restoration', 150.00, 240.00, 408.00, 1.1, 1.8, 3.0, array['main line','drain','snaking'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_hydro_jet', 'Drain Services', 'Hydro Jetting', 'Hydro Jetting', 'Hydro-jet line to remove heavy scale and buildup', 375.00, 600.00, 850.00, 2.8, 4.4, 6.3, array['drain','jetting','hydro'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/cost-to-unclog-snake-a-drain']),
      ('ir_shutoff_valve', 'Pipe Repair', 'Shutoff Valve Replacement', 'Shutoff Valve Replacement', 'Replace failed shutoff valve with quarter-turn valve', 175.00, 240.00, 320.00, 1.5, 2.0, 2.7, array['shutoff','valve','pipe'], 'Default baseline (insufficient source rows)', array[]::text[]),
      ('ir_pipe_leak', 'Pipe Repair', 'Pipe Leak Repair', 'Pipe Leak Repair', 'Repair leaking supply or drain section and pressure test', 203.75, 326.00, 554.20, 1.7, 2.7, 4.7, array['pipe','leak','repair'], 'Angi | Homeguide | Housecallpro 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm','https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_wheater_tank_install', 'Water Heater', 'Tank Water Heater Install', 'Tank Water Heater Install', 'Install tank water heater with code-compliant connections and startup', 965.00, 1544.00, 2624.80, 10.2, 12.0, 12.0, array['water heater','tank','install'], 'Angi | Homeguide | Housecallpro 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://homeguide.com/costs/water-heater-repair-cost','https://www.angi.com/articles/plumber-cost.htm','https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_wheater_tankless_install', 'Water Heater', 'Tankless Water Heater Install', 'Tankless Water Heater Install', 'Install tankless water heater and commission system', 800.00, 1280.00, 2176.00, 8.4, 12.0, 12.0, array['water heater','tankless','install'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_wheater_flush', 'Water Heater', 'Water Heater Flush', 'Water Heater Flush', 'Perform full flush and preventive maintenance', 175.00, 240.00, 320.00, 1.8, 2.5, 3.4, array['water heater','flush','maintenance'], 'Default baseline (insufficient source rows)', array[]::text[]),
      ('ir_emergency_leak', 'Emergency', 'Burst Pipe Emergency Response', 'Burst Pipe Emergency Response', 'Emergency response to active leak with stabilization and repair', 175.00, 240.00, 320.00, 1.7, 2.3, 3.0, array['emergency','burst','pipe','leak'], 'Default baseline (insufficient source rows)', array[]::text[]),
      ('ir_emergency_overflow', 'Emergency', 'Overflow Emergency Response', 'Overflow Emergency Response', 'Emergency response for overflow event and immediate mitigation', 150.00, 240.00, 350.00, 1.4, 2.3, 3.3, array['emergency','overflow','toilet'], 'Housecallpro 2026 normalized', array['https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_sink_install', 'Fixtures', 'Sink Installation', 'Sink Installation', 'Install sink fixture and verify proper sealing and drainage', 214.00, 342.40, 582.08, 1.4, 2.2, 3.7, array['sink','fixture','install'], 'Angi | Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm']),
      ('ir_shower_valve_replace', 'Fixtures', 'Shower Valve Replacement', 'Shower Valve Replacement', 'Replace shower valve and rebalance flow and temperature', 225.00, 360.00, 575.00, 1.4, 2.3, 3.6, array['shower','valve','replace'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_bathtub_install', 'Fixtures', 'Bathtub Installation', 'Bathtub Installation', 'Install bathtub and complete fixture and drain hookups', 750.00, 1200.00, 2040.00, 4.7, 7.6, 12.0, array['bathtub','tub','install'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_water_softener_install', 'Fixtures', 'Water Softener Installation', 'Water Softener Installation', 'Install water softener and test system operation', 480.00, 768.00, 1305.60, 3.0, 4.9, 8.2, array['water softener','install'], 'Angi | Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm']),
      ('ir_toilet_repair', 'Fixtures', 'Toilet Repair', 'Toilet Repair', 'Repair toilet fill, flush, seal, or clog-related issues', 100.00, 160.00, 272.00, 0.6, 1.0, 1.7, array['toilet','repair'], 'Angi | Homeguide | Housecallpro 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm','https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_drain_pipe_replacement', 'Drain Services', 'Drain Pipe Replacement', 'Drain Pipe Replacement', 'Repair or replace damaged drain pipe segments', 100.00, 160.00, 272.00, 0.7, 1.2, 2.0, array['drain','pipe','replacement'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_sewer_camera_inspection', 'Drain Services', 'Sewer Camera Inspection', 'Sewer Camera Inspection', 'Inspect sewer/drain line with camera and provide findings', 125.00, 200.00, 340.00, 0.9, 1.5, 2.5, array['sewer','camera','inspection'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_sewer_line_replacement', 'Drain Services', 'Sewer Line Replacement', 'Sewer Line Replacement', 'Replace damaged sewer main line and restore service', 2381.67, 3810.67, 6478.14, 12.0, 12.0, 12.0, array['sewer','line','replacement'], 'Homeguide | Housecallpro 2026 normalized', array['https://homeguide.com/costs/burst-pipe-repair-cost','https://homeguide.com/costs/plumber-cost','https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_gas_line_repair', 'Pipe Repair', 'Gas Line Repair', 'Gas Line Repair', 'Repair gas line and verify leak-safe operation', 180.00, 288.00, 489.60, 1.5, 2.4, 4.1, array['gas line','repair'], 'Angi | Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm']),
      ('ir_main_water_line_repair', 'Pipe Repair', 'Main Water Line Repair', 'Main Water Line Repair', 'Repair main water line leak and restore pressure', 400.00, 640.00, 1088.00, 3.4, 5.4, 9.2, array['main water line','repair'], 'Homeguide | Housecallpro 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_reroute_plumbing', 'Pipe Repair', 'Rerouting Plumbing', 'Rerouting Plumbing', 'Reroute plumbing for access, remodel, or damaged lines', 700.00, 1100.00, 1500.00, 5.9, 9.3, 12.0, array['reroute','plumbing'], 'Angi 2026 normalized', array['https://www.angi.com/articles/plumber-cost.htm']),
      ('ir_full_house_repipe', 'Pipe Repair', 'Full House Repipe', 'Full House Repipe', 'Replace major in-home plumbing runs with modern piping', 5798.00, 9276.80, 13542.00, 12.0, 12.0, 12.0, array['repipe','whole house'], 'Angi | Homeguide | Housecallpro 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm','https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_water_heater_repair', 'Water Heater', 'Water Heater Repair', 'Water Heater Repair', 'Diagnose and repair tank or tankless water heater faults', 150.00, 240.00, 408.00, 1.6, 2.5, 4.3, array['water heater','repair'], 'Angi | Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm']),
      ('ir_gas_valve_replacement', 'Water Heater', 'Gas Valve Replacement', 'Gas Valve Replacement', 'Replace water heater gas control valve and test system', 150.00, 240.00, 408.00, 1.6, 2.5, 4.3, array['gas valve','water heater'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_sump_pump_install', 'Pump Services', 'Sump Pump Installation', 'Sump Pump Installation', 'Install sump pump and verify discharge operation', 550.00, 750.00, 950.00, 4.6, 6.3, 8.0, array['sump pump','install'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_sump_pump_repair', 'Pump Services', 'Sump Pump Repair', 'Sump Pump Repair', 'Repair sump pump and restore pumping performance', 337.33, 539.73, 790.00, 2.8, 4.5, 6.7, array['sump pump','repair'], 'Angi | Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm']),
      ('ir_well_pump_repair', 'Pump Services', 'Well Pump Repair', 'Well Pump Repair', 'Repair well pump components and restore water delivery', 500.00, 750.00, 1000.00, 4.2, 6.3, 8.4, array['well pump','repair'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_emergency_service_call', 'Emergency', 'Emergency Service Call', 'Emergency Service Call', 'Urgent dispatch fee and first-hour diagnostics for emergency calls', 150.00, 240.00, 350.00, 1.4, 2.3, 3.3, array['emergency','service','call'], 'Housecallpro 2026 normalized', array['https://www.housecallpro.com/resources/marketing/how-to/how-to-price-plumbing-jobs/']),
      ('ir_plumbing_inspection', 'Inspection', 'Plumbing Inspection', 'Plumbing Inspection', 'Perform plumbing inspection and document findings', 125.00, 200.00, 340.00, 0.7, 1.1, 1.8, array['inspection','plumbing'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_septic_pumping', 'Septic', 'Septic Tank Pumping', 'Septic Tank Pumping', 'Pump septic tank and inspect condition', 250.00, 400.00, 650.00, 2.4, 3.8, 6.2, array['septic','pumping'], 'Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost']),
      ('ir_septic_repair', 'Septic', 'Septic Tank Repair', 'Septic Tank Repair', 'Repair septic system components and restore operation', 546.67, 874.67, 1486.94, 5.2, 8.3, 12.0, array['septic','repair'], 'Angi | Homeguide 2026 normalized', array['https://homeguide.com/costs/plumber-cost','https://www.angi.com/articles/plumber-cost.htm'])
  ) as t(
    id, category, subcategory, display_name, description,
    price_good, price_better, price_best,
    labor_hours_good, labor_hours_better, labor_hours_best,
    tags, source, source_urls
  )
)
insert into public.industry_rates (
  id, category, subcategory, display_name, description,
  price_good, price_better, price_best,
  labor_hours_good, labor_hours_better, labor_hours_best,
  labor_rate_per_hour,
  warranty_months_good, warranty_months_better, warranty_months_best,
  solution_good, solution_better, solution_best,
  tags, source, source_urls, is_active, updated_at
)
select
  id, category, subcategory, display_name, description,
  round(price_good, 2),
  round(price_better, 2),
  round(price_best, 2),
  round(labor_hours_good, 1),
  round(labor_hours_better, 1),
  round(labor_hours_best, 1),
  95.00,
  3, 12, 24,
  'Resolve immediate issue with standard parts and workmanship.',
  'Resolve root cause with upgraded parts and longer coverage.',
  'Future-proof solution with premium scope and maximum coverage.',
  tags,
  source,
  source_urls,
  true,
  now()
from seed_rates
on conflict (id) do update set
  category = excluded.category,
  subcategory = excluded.subcategory,
  display_name = excluded.display_name,
  description = excluded.description,
  price_good = excluded.price_good,
  price_better = excluded.price_better,
  price_best = excluded.price_best,
  labor_hours_good = excluded.labor_hours_good,
  labor_hours_better = excluded.labor_hours_better,
  labor_hours_best = excluded.labor_hours_best,
  tags = excluded.tags,
  source = excluded.source,
  source_urls = excluded.source_urls,
  is_active = excluded.is_active,
  updated_at = now();
